package Interfaces;

/**
* Interfaces/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* 25. lokakuuta 2018 8.54.09 EDT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Interfaces.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (Interfaces.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Interfaces.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Interfaces.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Interfaces.ServerInterfaceHelper.type ();
  }

}
